baseURL = "/"
languageCode = "en-us"
title = "GlueDB"
showToc = true
relativeURLs = true
disableKinds = ["taxonomy", "term"]
staticDir = ["static", "diagrams"]

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"

[markup]
  [markup.tableOfContents]
    ordered = false
[params.mermaid]
version = "10.8.0"