production:
  sessions:
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: <%= ENV['EDIDB_DB_NAME'] %>
      <% if ENV['EDIDB_DB_AUTH'] %>
      username: <%= ENV['EDIDB_DB_USERNAME'] %>
      password: <%= ENV['EDIDB_DB_PASSWORD'] %>
      <% end %>

      hosts:
        - <%= ENV['EDIDB_DB_HOST'] %>:<%= ENV['EDIDB_DB_PORT'] %>
      options:
        <% if ENV['EDIDB_DB_AUTH'] %>
        replica_set: <%= ENV['EDIDB_DB_REPLICA_SET_NAME'] %>
        <% end %> 

        skip_version_check: true
      # Change whether the session persists in safe mode by default.
      # (default: false)
      # safe: false

      # Change the default consistency model to :eventual or :strong.
      # :eventual will send reads to secondaries, :strong sends everything
      # to master. (default: :eventual)
      # consistency: :eventual

      # How many times Moped should attempt to retry an operation after
      # failure. (default: 30)
      # max_retries: 30

      # The time in seconds that Moped should wait before retrying an
      # operation on failure. (default: 1)
      # retry_interval: 1
      # Configure Mongoid specific options. (optional)
  options:
      # Configuration for whether or not to allow access to fields that do
      # not have a field definition on the model. (default: true)
      # allow_dynamic_fields: true

      # Enable the identity map, needed for eager loading. (default: false)
development:
  sessions:
    default:
      # Defines the name of the default database that Mongoid can connect to.
      # (required).
      database: <%= ENV['EDIDB_DB_NAME'] %>_dev
      <% if ENV['EDIDB_DB_AUTH'] %>
      username: <%= ENV['EDIDB_DB_USERNAME'] %>
      password: <%= ENV['EDIDB_DB_PASSWORD'] %>
      <% end %>

      hosts:
        - <%= ENV['EDIDB_DB_HOST'] %>:<%= ENV['EDIDB_DB_PORT'] %>
      options:
        <% if ENV['EDIDB_DB_AUTH'] %>
        replica_set: <%= ENV['EDIDB_DB_REPLICA_SET_NAME'] %>
        <% end %>

        skip_version_check: true

  options:
