FROM  public.ecr.aws/ideacrew/mongodb:2.6.12

ENV HOME /mongo
RUN mkdir -p $HOME
WORKDIR $HOME
COPY . $HOME

RUN apt-get update && \
    apt-get install -y wget curl unzip zip

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && \
    unzip awscliv2.zip && ./aws/install

RUN chmod 744 mongo_backup.sh
RUN rm -f awscliv2.zip && rm -rf aws
