tax_document:
  2020:
    slcsp: '94506DC0390006-01'
    new:
      template:
        unassisted: '2020-1095A-NEW-UQHP.pdf'
        assisted: '2020-1095A-NEW-AQHP.pdf'
    void:
      template:
        active_false: '2020-1095A-VOID-ACTIVE-FALSE.pdf'
        active_true: '2020-1095A-VOID-ACTIVE-TRUE.pdf'
    coverage_page_no: 3
  2021:
    slcsp: '48396ME0710074-01'
    new:
      template:
        unassisted: '2020-1095A-NEW-UQHP.pdf'
        assisted: '2020-1095A-NEW-AQHP.pdf'
    void:
      template:
        active_false: '2020-1095A-VOID-ACTIVE-FALSE.pdf'
        active_true: '2020-1095A-VOID-ACTIVE-TRUE.pdf'
    coverage_page_no: 3
  documents_root_path: '/tmp/'
  documents_folder: 'irs_notices'
