tax_document:
  2014:
    slcsp: "94506DC0390006-01"
    new:
      template: "1095a_template.pdf"
    void:
      template: "1095a_template_void.pdf"
    catastrophic:
      new: 
        template: "1095a_template_catastrophic.pdf"
      corrected: 
        template: "1095a_template_corrected_2.pdf"
    coverage_page_no: 3
  2015:
    slcsp: "94506DC0390006-01"
    new:
      template: "1095a_template_2015.pdf"
    void:
      template: "1095a_template_void_2015.pdf"
    catastrophic:
      template: "1095a_template_2015_catastrophic_aptc.pdf"
    coverage_page_no: 3
  2016:
    slcsp: "94506DC0390006-01"
    new:
      template:
        unassisted: "2016-1095A-NEW-UQHP.pdf"
        assisted: "2016-1095A-NEW-AQHP.pdf"
    void:
      template: "2016-1095A-VOID.pdf"
    coverage_page_no: 5
  2017:
    slcsp: "86052DC0400001-01"
    new:
      template:
        unassisted: "2017-1095A-NEW-UQHP.pdf"
        assisted: "2017-1095A-NEW-AQHP.pdf"
    void:
      template:
        active_false: "2017-1095A-VOID-ACTIVE-FALSE.pdf"
        active_true: "2017-1095A-VOID-ACTIVE-TRUE.pdf"
    coverage_page_no: 3
  2018:
    slcsp: "94506DC0390014-01"
    new:
      template:
        unassisted: "2018-1095A-NEW-UQHP.pdf"
        assisted: "2018-1095A-NEW-AQHP.pdf"
    void:
      template:
        active_false: "2018-1095A-VOID-ACTIVE-FALSE.pdf"
        active_true: "2018-1095A-VOID-ACTIVE-TRUE.pdf"
    coverage_page_no: 3
  2019:
    slcsp: "86052DC0400001-01"
    new:
      template:
        unassisted: "2019-1095A-NEW-UQHP.pdf"
        assisted: "2019-1095A-NEW-AQHP.pdf"
    void:
      template:
        active_false: '2019-1095A-VOID-ACTIVE-FALSE.pdf'
        active_true: '2019-1095A-VOID-ACTIVE-TRUE.pdf'
    coverage_page_no: 3
  2020:
    slcsp: "94506DC0390006-01"
    new:
      template:
        unassisted: '2020-1095A-NEW-UQHP.pdf'
        assisted: '2020-1095A-NEW-AQHP.pdf'
    void:
      template:
        active_false: '2020-1095A-VOID-ACTIVE-FALSE.pdf'
        active_true: '2020-1095A-VOID-ACTIVE-TRUE.pdf'
    coverage_page_no: 3
  2021:
    slcsp: "94506DC0390005-01"
    new:
      template:
        unassisted: '2021-1095A-NEW-UQHP.pdf'
        assisted: '2021-1095A-NEW-AQHP.pdf'
    void:
      template:
        active_false: '2021-1095A-VOID-ACTIVE-FALSE.pdf'
        active_true: '2021-1095A-VOID-ACTIVE-TRUE.pdf'
    coverage_page_no: 3
  2022:
    slcsp: "94506DC0390006-01"
    new:
      template:
        unassisted: '2022-1095A-NEW-UQHP.pdf'
        assisted: '2022-1095A-NEW-AQHP.pdf'
    void:
      template:
        active_false: '2022-1095A-VOID-ACTIVE-FALSE.pdf'
        active_true: '2022-1095A-VOID-ACTIVE-TRUE.pdf'
    coverage_page_no: 3
  2023:
    slcsp: "94506DC0390006-01"
    new:
      template:
        unassisted: '2023-1095A-NEW-UQHP.pdf'
        assisted: '2023-1095A-NEW-AQHP.pdf'
    void:
      template:
        active_false: '2023-1095A-VOID-ACTIVE-FALSE.pdf'
        active_true: '2023-1095A-VOID-ACTIVE-TRUE.pdf'
    coverage_page_no: 3
  documents_root_path: '/tmp/'
  documents_folder: 'irs_notices'

cms_pbp_generation:
  cms_pbp_source_sbm_id: "FEP0020DC"
  hios_prefix_ids: ["86052", "78079", "94506", "81334", "92479", "95051"]
  subdirectory_prefix: 'DCHBX'

irs_h41_generation:
  subdirectory_prefix: 'DCHBX_H41'
  irs_h41_source_sbm_id: 'FEP0020DC'
  h41_directory_sub_prefix: 'DSH.EOYIN'

irs_h36_generation:
  irs_h36_source_sbm_id: 'FEP0020DC'
  h36_directory_sub_prefix: 'DSH.EOMIN'

irs_1095A:
  subdirectory_prefix: 'DCEXCHANGE'
