site:
  short_name: "Access Health CT"
  long_name: "Access Health Glue DB"
  copyright_period_start: "2014"

  
  social_media:
    facebook_url: ""

contact_center:
  name: "Department of Human Services"
  address: "P.O. Box 91560"
  city: "Hartford"
  state_abbreviation: "CT"
  postal_code: "20090"
