name: Docs
on:
  workflow_dispatch:
  push:
    branches:
      - 'me_carrier_boarding'

jobs:
  docs:
    runs-on: ubuntu-22.04
    steps:
      - name: Get Packages for Ruby Prerequisites
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git libntirpc-dev libxml2 libxml2-dev curl libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
      - name: Install libssl1.0-dev from bionic sources
        run: |
          echo 'deb http://security.ubuntu.com/ubuntu bionic-security main' | sudo tee -a /etc/apt/sources.list.d/bionic-security.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
          sudo apt update && apt-cache policy libssl1.0-dev
          sudo apt-get -y install libssl1.0-dev
      - uses: actions/checkout@v3
      - name: Download Ruby
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.10.tar.bz2
      - name: Cache Ruby
        id: cache-ruby
        uses: actions/cache@v3
        with:
          path: ruby-2.1.10
          key: ${{ runner.os }}-gluedb-ruby-${{ hashFiles('**/Gemfile.lock', 'ruby-2.1.10.tar.bz2', '/usr/local/bin/ruby') }}
          restore-keys: |
            ${{ runner.os }}-gluedb-ruby-${{ hashFiles('**/Gemfile.lock', 'ruby-2.1.10.tar.bz2', '/usr/local/bin/ruby') }}
      - name: Build Ruby
        if: steps.cache-ruby.outputs.cache-hit != 'true'
        run: |
          tar xjf ruby-2.1.10.tar.bz2
          cd ruby-2.1.10 && ./configure --disable-install-doc && make -j 2
      - name: Install Ruby
        run: |
          cd ruby-2.1.10
          sudo make install
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
          node-version: "14"
      - name: install hugo
        run: sudo snap install hugo --channel=extended
      - uses: actions/setup-java@v1
        with:
          java-version: "8"
          java-package: jdk
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gluedb-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gluedb-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          sudo gem install bundler -v '1.17.3'
          export BUNDLE_GITHUB__COM=${{ secrets.dchbx_deployments_token }}:x-oauth-basic
          bundle config path vendor/bundle
          bundle install
      - name: build rdoc
        run: |
          cp config/exchange.yml.example config/exchange.yml
          bundle exec yard && cp -rf ./doc ./hugo/static/
      - name: run hugo
        run: |
          cd hugo && npm install && ./build_hugo.sh
      - uses: nelonoel/branch-name@v1.0.1
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.IC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.IC_AWS_SECRET_ACCESS_KEY }}
          SOURCE_DIR: hugo/public
          DEST_DIR: ${{ env.BRANCH_NAME }}
      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ secrets.DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
          AWS_ACCESS_KEY_ID: ${{ secrets.IC_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.IC_AWS_SECRET_ACCESS_KEY }}
