name: Docs
on:
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-18.04
    steps:
      - name: Get Packages for Ruby Prerequisites
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git curl libssl1.0-dev libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
      - name: Install Ruby
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.10.tar.bz2
          tar xjf ruby-2.1.10.tar.bz2
          cd ruby-2.1.10 && ./configure && make -j 2
          sudo make install
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2.1.2
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
          node-version: '12'
      - name: install hugo
        run: sudo snap install hugo --channel=extended
      - uses: actions/setup-java@v3
        with:
          java-version: '8'
          java-package: jdk
      - name: Setup Graphviz
        uses: ts-graphviz/setup-graphviz@v1
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gluedb-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gluedb-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          sudo gem install bundler -v '1.17.3'
          export BUNDLE_GITHUB__COM=${{ secrets.dchbx_deployments_token }}:x-oauth-basic
          bundle config path vendor/bundle
          bundle install
      - name: build rdoc
        run: |
          cp config/exchange.yml.example config/exchange.yml
          bundle exec yard && cp -rf ./doc ./hugo/static/
      - name: run hugo
        run: |
          cd hugo && npm install && ./build_hugo.sh
      - uses: nelonoel/branch-name@v1.0.1
      - uses: jakejarvis/s3-sync-action@master
        env:
          AWS_S3_BUCKET: ${{ secrets.YARD_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.YARD_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.YARD_SECRET_ACCESS_KEY }}
          SOURCE_DIR: hugo/public
          DEST_DIR: ${{ env.BRANCH_NAME }}
