name: RSpec
on: push

jobs:
  rspec:
    runs-on: ubuntu-20.04
    steps:
      - name: Get Packages for Ruby Prerequisites
        run: |
          sudo apt-get -y update
          sudo apt-get -y install git libntirpc-dev libxml2 libxml2-dev curl libreadline-dev zlib1g-dev autoconf bison build-essential libyaml-dev libreadline-dev libncurses5-dev libffi-dev libgdbm-dev
      - name: Install libssl1.0-dev from bionic sources
        run: |
          echo 'deb http://security.ubuntu.com/ubuntu bionic-security main' | sudo tee -a /etc/apt/sources.list.d/bionic-security.list
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 3B4FE6ACC0B21F32
          sudo apt update && apt-cache policy libssl1.0-dev
          sudo apt-get -y install libssl1.0-dev
      - name: Install Ruby
        run: |
          curl -O https://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.10.tar.bz2
          tar xjf ruby-2.1.10.tar.bz2
          cd ruby-2.1.10 && ./configure && make -j 2
          sudo make install
      - name: Launch MongoDB
        uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: 3.4
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          # Version Spec of the version to use.  Examples: 10.x, 10.15.1, >=10.15.0, lts
          node-version: 9.11.1
      - uses: actions/checkout@v3
      - name: Cache Gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gluedb-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gluedb-gems-${{ hashFiles('**/Gemfile.lock') }}
      - name: bundle install
        run: |
          sudo gem install bundler -v '1.17.3'
          export BUNDLE_GITHUB__COM=${{ secrets.dchbx_deployments_token }}:x-oauth-basic
          bundle config path vendor/bundle
          export BUNDLE_GITHUB__COM=${{ secrets.dchbx_deployments_token }}:x-oauth-basic
          bundle install
      - name: run tests
        run: |
          cp config/exchange.yml.example config/exchange.yml
          bundle exec rspec
