name: Quality Workbench
on:
  push:
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: qb-${{ github.ref }}
  cancel-in-progress: true

env:
  BUNDLE_GITHUB__COM: ${{ secrets.dchbx_deployments_token }}:x-oauth-basic

jobs:
  rspec:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
      - name: Restore project gems
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
          restore-keys: |
            ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}-${{ hashFiles('**/Gemfile' ) }}
            ${{ runner.os }}-
      - name: Install project gems
        run: |
          gem update --system
          bundle config path vendor/bundle
          bundle install
      - uses: wbari/start-mongoDB@v0.2
        with:
          mongoDBVersion: 3.4
      - name: run tests
        run: |
          cp config/exchange.yml.example config/exchange.yml
          bundle exec rspec
